#############################################################################
# Makefile for building: stokes
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 5? 31 22:29:02 2016
# Project:  stokes.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o makefile stokes.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -w -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -w -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iinclude -I/usr/include/qt4 -I/usr/include/qwt -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lqwt -lboost_thread -lboost_system -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ut_widget.cpp \
		DataCollection/objmanager.cpp \
		DataCollection/spectrograph.cpp \
		DataProcessing/processor.cpp \
		UI/plot.cpp \
		UI/widget.cpp \
		UI/mainwindow.cpp \
		UI/toolpanel.cpp \
		UI/infopanel.cpp \
		UI/graphicspanel.cpp \
		UI/threadspanel.cpp \
		UI/analysepanel.cpp \
		UI/application.cpp \
		Universal/complex.cpp \
		Universal/innerdata.cpp \
		Universal/math.cpp moc_plot.cpp \
		moc_mainwindow.cpp \
		moc_toolpanel.cpp \
		moc_infopanel.cpp \
		moc_graphicspanel.cpp \
		moc_threadspanel.cpp \
		moc_analysepanel.cpp \
		moc_application.cpp
OBJECTS       = ut_widget.o \
		objmanager.o \
		spectrograph.o \
		processor.o \
		plot.o \
		widget.o \
		mainwindow.o \
		toolpanel.o \
		infopanel.o \
		graphicspanel.o \
		threadspanel.o \
		analysepanel.o \
		application.o \
		complex.o \
		innerdata.o \
		math.o \
		moc_plot.o \
		moc_mainwindow.o \
		moc_toolpanel.o \
		moc_infopanel.o \
		moc_graphicspanel.o \
		moc_threadspanel.o \
		moc_analysepanel.o \
		moc_application.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_off.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		stokes.pro
QMAKE_TARGET  = stokes
DESTDIR       = 
TARGET        = stokes

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

makefile: stokes.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_off.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o makefile stokes.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_off.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o makefile stokes.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/stokes1.0.0 || $(MKDIR) .tmp/stokes1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/stokes1.0.0/ && $(COPY_FILE) --parents testsuite.h include/DataCollection/objmanager.h include/DataCollection/spectrograph.h include/DataProcessing/processor.h include/UI/plot.h include/UI/widget.h include/UI/mainwindow.h include/UI/toolpanel.h include/UI/infopanel.h include/UI/graphicspanel.h include/UI/threadspanel.h include/UI/analysepanel.h include/UI/application.h include/Universal/complex.h include/Universal/innerdata.h include/Universal/math.h .tmp/stokes1.0.0/ && $(COPY_FILE) --parents ut_widget.cpp DataCollection/objmanager.cpp DataCollection/spectrograph.cpp DataProcessing/processor.cpp UI/plot.cpp UI/widget.cpp UI/mainwindow.cpp UI/toolpanel.cpp UI/infopanel.cpp UI/graphicspanel.cpp UI/threadspanel.cpp UI/analysepanel.cpp UI/application.cpp Universal/complex.cpp Universal/innerdata.cpp Universal/math.cpp .tmp/stokes1.0.0/ && $(COPY_FILE) --parents app_en.ts .tmp/stokes1.0.0/ && (cd `dirname .tmp/stokes1.0.0` && $(TAR) stokes1.0.0.tar stokes1.0.0 && $(COMPRESS) stokes1.0.0.tar) && $(MOVE) `dirname .tmp/stokes1.0.0`/stokes1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/stokes1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_plot.cpp moc_mainwindow.cpp moc_toolpanel.cpp moc_infopanel.cpp moc_graphicspanel.cpp moc_threadspanel.cpp moc_analysepanel.cpp moc_application.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_plot.cpp moc_mainwindow.cpp moc_toolpanel.cpp moc_infopanel.cpp moc_graphicspanel.cpp moc_threadspanel.cpp moc_analysepanel.cpp moc_application.cpp
moc_plot.cpp: include/UI/plot.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/UI/plot.h -o moc_plot.cpp

moc_mainwindow.cpp: include/UI/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/UI/mainwindow.h -o moc_mainwindow.cpp

moc_toolpanel.cpp: include/UI/toolpanel.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/UI/toolpanel.h -o moc_toolpanel.cpp

moc_infopanel.cpp: include/UI/infopanel.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/UI/infopanel.h -o moc_infopanel.cpp

moc_graphicspanel.cpp: include/UI/graphicspanel.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/UI/graphicspanel.h -o moc_graphicspanel.cpp

moc_threadspanel.cpp: include/UI/threadspanel.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/UI/threadspanel.h -o moc_threadspanel.cpp

moc_analysepanel.cpp: include/UI/analysepanel.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/UI/analysepanel.h -o moc_analysepanel.cpp

moc_application.cpp: include/UI/application.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) include/UI/application.h -o moc_application.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

ut_widget.o: ut_widget.cpp testsuite.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ut_widget.o ut_widget.cpp

objmanager.o: DataCollection/objmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objmanager.o DataCollection/objmanager.cpp

spectrograph.o: DataCollection/spectrograph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spectrograph.o DataCollection/spectrograph.cpp

processor.o: DataProcessing/processor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processor.o DataProcessing/processor.cpp

plot.o: UI/plot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plot.o UI/plot.cpp

widget.o: UI/widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o UI/widget.cpp

mainwindow.o: UI/mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o UI/mainwindow.cpp

toolpanel.o: UI/toolpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolpanel.o UI/toolpanel.cpp

infopanel.o: UI/infopanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o infopanel.o UI/infopanel.cpp

graphicspanel.o: UI/graphicspanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicspanel.o UI/graphicspanel.cpp

threadspanel.o: UI/threadspanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o threadspanel.o UI/threadspanel.cpp

analysepanel.o: UI/analysepanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o analysepanel.o UI/analysepanel.cpp

application.o: UI/application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o application.o UI/application.cpp

complex.o: Universal/complex.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o complex.o Universal/complex.cpp

innerdata.o: Universal/innerdata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o innerdata.o Universal/innerdata.cpp

math.o: Universal/math.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o math.o Universal/math.cpp

moc_plot.o: moc_plot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plot.o moc_plot.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_toolpanel.o: moc_toolpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolpanel.o moc_toolpanel.cpp

moc_infopanel.o: moc_infopanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_infopanel.o moc_infopanel.cpp

moc_graphicspanel.o: moc_graphicspanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphicspanel.o moc_graphicspanel.cpp

moc_threadspanel.o: moc_threadspanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_threadspanel.o moc_threadspanel.cpp

moc_analysepanel.o: moc_analysepanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_analysepanel.o moc_analysepanel.cpp

moc_application.o: moc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_application.o moc_application.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

